# Generated by Django 5.2.7 on 2025-10-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_navo', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='championstat',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='rune',
            name='rune_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='championstat',
            constraint=models.UniqueConstraint(fields=('summoner', 'champion'), name='uniq_summoner_champion'),
        ),
    ]
