# Generated by Django 5.2.7 on 2025-10-27 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_navo', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='championstat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='matchsummoners',
            name='item0',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item0', to='lol_navo.item'),
        ),
        migrations.AddField(
            model_name='matchsummoners',
            name='item1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item1', to='lol_navo.item'),
        ),
        migrations.AddField(
            model_name='matchsummoners',
            name='item2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item2', to='lol_navo.item'),
        ),
        migrations.AddField(
            model_name='matchsummoners',
            name='item3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item3', to='lol_navo.item'),
        ),
        migrations.AddField(
            model_name='matchsummoners',
            name='item4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item4', to='lol_navo.item'),
        ),
        migrations.AddField(
            model_name='matchsummoners',
            name='item5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item5', to='lol_navo.item'),
        ),
        migrations.AddField(
            model_name='matchsummoners',
            name='item6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item6', to='lol_navo.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.PositiveSmallIntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='matchsummoners',
            name='champion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='champion', to='lol_navo.champion'),
        ),
        migrations.AlterField(
            model_name='matchsummoners',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_entries', to='lol_navo.match'),
        ),
        migrations.AlterField(
            model_name='matchsummoners',
            name='summoner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='lol_navo.summoner'),
        ),
        migrations.AlterField(
            model_name='rune',
            name='rune_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='championstat',
            constraint=models.UniqueConstraint(fields=('summoner', 'champion'), name='uniq_summoner_champion'),
        ),
    ]
