# Generated by Django 5.2.7 on 2025-10-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_navo', '0002_alter_championstat_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='icon',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='champion',
            name='champion_banrate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='champion',
            name='champion_pickrate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='champion',
            name='champion_winrate',
            field=models.FloatField(default=0),
        ),
    ]
