# Generated by Django 5.2.7 on 2025-10-26 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_navo', '0003_alter_match_id_alter_matchsummoners_champion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='matchsummoners',
            name='champion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='champion', to='lol_navo.champion'),
        ),
        migrations.AlterField(
            model_name='matchsummoners',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_entries', to='lol_navo.match'),
        ),
        migrations.AlterField(
            model_name='matchsummoners',
            name='summoner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='lol_navo.summoner'),
        ),
    ]
