# Generated by Django 5.2.7 on 2025-11-07 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_navo', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='championstat',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='champion',
            name='champion_banrate',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='champion_description',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='champion_name',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='champion_pickrate',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='champion_role',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='champion_winrate',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_value',
        ),
        migrations.AddField(
            model_name='champion',
            name='armor',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='armor_per_level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='attack',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='attack_damage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='attack_damage_per_level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='attack_range',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='attack_speed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='attack_speed_per_level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='bans',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='crit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='crit_per_level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='defense',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='description',
            field=models.CharField(default='', max_length=2550),
        ),
        migrations.AddField(
            model_name='champion',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='hp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='hp_per_level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='hp_regen',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='hp_regen_per_level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='icon',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='champion',
            name='magic',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='move_speed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='mp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='mp_per_level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='mp_regen',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='mp_regen_per_level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='name',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='champion',
            name='partype',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='champion',
            name='picks',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='spell_block',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='spell_block_per_level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='champion',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='champion',
            name='wins',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='championstat',
            name='games',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='championstat',
            name='kda',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='championstat',
            name='point',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='championstat',
            name='winrate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='base_gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='builds_from',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='item',
            name='builds_into',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='item',
            name='colloq',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='consume_on_full',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='consumed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='depth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='effect',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='item',
            name='hide_from_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='in_store',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='maps',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='plaintext',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='purchasable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='required_ally',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='item',
            name='required_buff_currency_cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='required_buff_currency_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='item',
            name='required_champion',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='item',
            name='sell_gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='special_recipe',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='stacks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='stats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='item',
            name='total_gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='value',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchsummoners',
            name='item0',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item0', to='lol_navo.item'),
        ),
        migrations.AddField(
            model_name='matchsummoners',
            name='item1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item1', to='lol_navo.item'),
        ),
        migrations.AddField(
            model_name='matchsummoners',
            name='item2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item2', to='lol_navo.item'),
        ),
        migrations.AddField(
            model_name='matchsummoners',
            name='item3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item3', to='lol_navo.item'),
        ),
        migrations.AddField(
            model_name='matchsummoners',
            name='item4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item4', to='lol_navo.item'),
        ),
        migrations.AddField(
            model_name='matchsummoners',
            name='item5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item5', to='lol_navo.item'),
        ),
        migrations.AddField(
            model_name='matchsummoners',
            name='item6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item6', to='lol_navo.item'),
        ),
        migrations.AlterField(
            model_name='championstat',
            name='summoner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='lol_navo.summoner'),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.PositiveSmallIntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='matchsummoners',
            name='champion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='champion', to='lol_navo.champion'),
        ),
        migrations.AlterField(
            model_name='matchsummoners',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_entries', to='lol_navo.match'),
        ),
        migrations.AlterField(
            model_name='matchsummoners',
            name='summoner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='lol_navo.summoner'),
        ),
        migrations.AlterField(
            model_name='rune',
            name='rune_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='championstat',
            constraint=models.UniqueConstraint(fields=('summoner', 'champion'), name='uniq_summoner_champion'),
        ),
        migrations.RemoveField(
            model_name='championstat',
            name='champion_games',
        ),
        migrations.RemoveField(
            model_name='championstat',
            name='champion_kda',
        ),
        migrations.RemoveField(
            model_name='championstat',
            name='champion_point',
        ),
        migrations.RemoveField(
            model_name='championstat',
            name='champion_winrate',
        ),
    ]
