# Generated by Django 5.2.7 on 2025-11-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_navo', '0002_alter_championstat_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='builds_from',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
