# Generated by Django 5.2.7 on 2025-11-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_navo', '0003_alter_item_builds_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='builds_into',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
