# Generated by Django 5.2.7 on 2025-11-08 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_navo', '0004_alter_item_builds_into'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='consume_on_full',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
