# Generated by Django 5.2.7 on 2025-11-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_navo', '0005_alter_item_consume_on_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='consume_on_full',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
