# Generated by Django 5.2.7 on 2025-11-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_navo', '0006_alter_item_consume_on_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='consumed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
