# Generated by Django 5.2.7 on 2025-11-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_navo', '0007_alter_item_consumed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='effect',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
