# Generated by Django 5.2.7 on 2025-11-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_navo', '0008_alter_item_effect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='hide_from_all',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
