# Generated by Django 5.2.7 on 2025-11-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_navo', '0009_alter_item_hide_from_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='in_store',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
